package com.udacity.project4.utils

object Constants {
    const val ACTION_GEOFENCE = "ACTION_GEOFENCE"
    const val GEOFENCE_RADIUS_IN_METERS = 200f


    const val REQUEST_TURN_DEVICE_LOCATION_ON = 2
    const val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 3
    const val REQUEST_FOREGROUND_AND_BACKGROUND_PERMISSION_RESULT_CODE = 4


}